[package]
org = "ballerinax"
name = "confluent.cavroserdes"
version = "1.0.1"
authors = ["Ballerina"]
export=["confluent.cavroserdes"]
keywords = ["confluent", "schema_registry", "avro", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerinax-confluent.cavroserdes"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "confluent.cavroserdes-native"
version = "1.0.1"
path = "../native/build/libs/confluent.cavroserdes-native-1.0.1.jar"
